---
language: c++
compiler: clang
dist: bionic
addons:
    snaps:
        - name: cmake
          confinement: classic

git:
    depth: 1

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
