---
working_dir: "/home/dan/workspace/library-metamorphic-testing/"
api_fuzzer_file: "./config_files/api_fuzzer_gmp_integer.yaml"
meta_test_file: "./config_files/set_meta_tests_gmp_integer.yaml"
test_emitter_output_file: "./out/test.cpp"
meta_runner:
# Path setup
    test_emitter_path: "./build/test_emitter"
    lib_path: "./libs"
    lib_build_dir: ~
    lib_coverage_dir: ~
    test_compile_dir: "./out"
# Test runtime setup
    test_compile_bin: "./compile_gmp.sh"
    test_source_path: "./out/test.cpp"
    test_run_path: "./out/test"
    default_timeout: 60
# Runner output setup
    output_folder: "./output"
    log_file_path: "./meta_test.log"
    stat_log_file_path: "./meta_test_stats.log"
    output_tests_folder: "./out_tests/"
    coverage_output_dir: "./coverage/"

