---
working_dir: "/home/sentenced/Documents/Internships/2018_ETH/work/sets"
meta_runner:
    isl_tester_path: "./build/test_emitter"
    lib_path: "./libs"
    test_compile_dir: "./out"
    test_compile_bin: "./compile_omega.sh"
    test_source_path: "./out/test.cpp"
    test_run_path: "./out/test"
    test_coverage_output_dir: "./out/coverage"
    log_file_path: "./out/meta_test.log"
    output_tests_folder: "./out/out_tests/"
    default_timeout: 30
set_meta_tester:
    meta_tests_file: "./config_files/set_meta_tests_omega.yaml"
    output_file: "./out/test.cpp"
