---
- working_dir = "/home/sentenced/Documents/Internships/2018_ETH/work/sets"
- meta_runner
    - isl_tester_path = "./build/isl_tester"
    - test_compile_dir = "./out"
    - test_source_path = "./out/test.cpp"
    - test_coverage_output_dir = "./out/coverage"
    - log_file_path = "./out/meta_test.log"
    - output_tests_folder = "./out/out_tests/"
    - default_timeout = 30

- set_meta_tester
    - meta_tests_file = "./config_files/set_meta_tests.yaml"
    - output_file = "./out/test.cpp"
