---
working_dir : "/home/isl_testing/isl-metamorphic-testing"
meta_runner :
    isl_tester_path : "./build/test_emitter"
    lib_path: "./libs"
    test_compile_dir : "./out"
    test_compile_bin : "./compile_isl.sh"
    test_source_path : "./out/test_4.cpp"
    test_run_path : "./out/test_4"
    test_coverage_output_dir : "./out/coverage"
    log_file_path : "./out/meta_test_4.log"
    output_tests_folder : "./out/out_tests_4/"
    default_timeout : 60
set_meta_tester :
    meta_tests_file : "./config_files/set_meta_tests_isl.yaml"
    output_file : "./out/test.cpp"
