---
working_dir: "/home/sentenced/Documents/Internships/2018_ETH/work/sets/"
api_fuzzer_file: "./config_files/isl/api_fuzzer_isl.yaml"
meta_test_file: "./config_files/isl/set_meta_tests_isl.yaml"
test_emitter_output_file: "./out/test.cpp"
meta_runner:
# Path setup
    test_emitter_path: "./build/test_emitter"
    lib_path: "./libs_local"
    include_path: "./include_local"
    lib_build_dir: ""
    lib_coverage_dir: ""
    test_compile_dir: "./out"
# Test runtime setup
    test_compile_bin: "./compile_isl.sh"
    test_source_path: "./out/test.cpp"
    test_run_path: "./out/test"
    default_timeout: 60
# Runner output setup
    output_folder: "./output"
    log_file_path: "./meta_test.log"
    stat_log_file_path: "./meta_test_stats.log"
    output_tests_folder: "./out_tests/"
    coverage_output_dir: "./coverage/"

